apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fuchicorp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-fuchicorp-prod

spec:
  rules:

  - host: nexus.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: nexus-fuchicorp-service
          servicePort: {{ .Values.nexusport }}

  - host: vault.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: vault-fuchicorp-service
          servicePort: {{ .Values.vaultport }}
  tls:
  - hosts:
    - vault.fuchicorp.com
    - nexus.fuchicorp.com
    - grafana.fuchicorp.com
    secretName: tls-prod-cert
